name: First Workflow 
on:
  push:
    branches:
      -"main"


jobs:
  first-pipline:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: run bash command
        run: echo "first workflow"
        shell: bash