name: ci workflow
on:
  pull_request:
    branches:
      - "main"
jobs:
  ci-workflow:
    name: ci workflow
    runs-on: ubuntu-latest
    steps:
      - name: build the app
        run: echo " Hello Mohamed"
        shell: bash