name: First Run
on: 
  push:
    branches:
      - "main"

jobs:
  first-run:
    name: first job
    runs-on: ubuntu:latest
    steps:
      - name: run bash command
        run: echo "Hello Mesbah From First Run"
        shell: bash